window:
  size: 120
  stride: 60
  drop_last: true
rr0:
  enabled: true
  mode: ratio
  baseline:
    method: first_k
    k: 30
detrend:
  enabled: true
  method: ema
  ema_alpha: 0.05
  poly_deg: 1
standardize:
  enabled: true
  per_device: true
  eps: 1.0e-6
temp_humid:
  enabled: true
