inherit: "configs/preprocess/common.yaml"
overrides:
  window: {size: 256, stride: 64}
  rr0: {enabled: true, mode: "ratio", baseline: {method: "first_k", k: 100}}
  detrend: {enabled: true, method: "ema", ema_alpha: 0.015}
  standardize: {enabled: true, per_device: false}
  temp_humid: {enabled: false}
