obp_list: configs/prior/obp_list.yaml
voc_map: configs/prior/voc_map.yaml
input:
  glob: docking/logs/**/*
  format: auto
  required_cols: [obp, ligand, affinity]
metrics:
  order: [min_affinity, p25_affinity, median_affinity, p75_affinity, mean_affinity, std_affinity, best_rmsd, top3_mean_affinity]
  flip_sign: [affinity]
scaling:
  method: zscore
  eps: 1.0e-6
  fillna: mean
defaults:
  fill: mean
output:
  table_csv: docking/out/prior_table.csv
  qc_json: docking/out/prior_qc.json
