uci_drift:
  root: data/uci_drift
  files:
    pattern: "**/*.csv"
  mapping:
    dataset: UCI_DRIFT
    time: time
    sensor_cols: [R1, R2, R3, R4, R5, R6, R7, R8]
    gas: gas
    conc: concentration
    temp: temp
    humid: humid
    device_id: device
    session_id: session
    stage: stage
    batch_id: batch
    sampling_rate: 100.0
  splits:
    train:
      forward_batches: [1, 2, 3, 4, 5, 6]
    val:
      forward_batches: [7]
    test:
      forward_batches: [8, 9, 10]
  synthetic:
    enabled: true
    per_split:
      train: 3
      val: 1
      test: 1
    sensors: 8
    length: 240
    gases: [ETHANOL, METHANE, TOLUENE]

twin:
  root: data/twin
  files:
    pattern: "**/*.csv"
  mapping:
    dataset: TWIN
    time: time
    sensor_cols: [S1, S2, S3, S4, S5, S6, S7, S8]
    gas: gas
    conc: concentration
    temp: temp
    humid: humid
    device_id: device
    session_id: session
    stage: stage
    batch_id: batch
    sampling_rate: 50.0
  splits:
    train:
      devices: [1]
    val:
      devices: [2]
    test:
      devices: [3]
    lodo_template:
      holdout_devices: [1, 2, 3]
  synthetic:
    enabled: true
    per_split:
      train: 2
      val: 1
      test: 1
    sensors: 8
    length: 180
    gases: [ETHANOL, ACETONE, AMMONIA]

tempmod:
  root: data/tempmod
  files:
    pattern: "**/*.csv"
  mapping:
    dataset: TEMP_MOD
    time: time
    sensor_cols: [C1, C2, C3, C4, C5, C6]
    gas: gas
    conc: concentration
    temp: temp
    humid: humid
    device_id: device
    session_id: session
    stage: cycle
    batch_id: batch
    sampling_rate: 25.0
  splits:
    train:
      include_cycles: [0, 1, 2]
    val:
      include_cycles: [3]
    test:
      include_cycles: [4]
  synthetic:
    enabled: true
    per_split:
      train: 2
      val: 1
      test: 1
    sensors: 6
    length: 200
    gases: [METHANE, BENZENE]

home:
  root: data/home
  files:
    pattern: "**/*.csv"
  mapping:
    dataset: HOME
    time: time
    sensor_cols: [H1, H2, H3, H4]
    gas: activity
    conc: concentration
    temp: temp
    humid: humid
    device_id: room
    session_id: session
    stage: stage
    batch_id: day
    sampling_rate: 5.0
  splits:
    train:
      include_days: [1, 2, 3]
    val:
      include_days: [4]
    test:
      include_days: [5]
  synthetic:
    enabled: true
    per_split:
      train: 2
      val: 1
      test: 1
    sensors: 4
    length: 300
    gases: [COOKING, CLEANING]

dynamic:
  root: data/dynamic
  files:
    pattern: "**/*.csv"
  mapping:
    dataset: DYNAMIC
    time: time
    sensor_cols: [D1, D2, D3, D4, D5, D6, D7]
    gas: gas
    conc: concentration
    temp: temp
    humid: humid
    device_id: rig
    session_id: session
    stage: stage
    batch_id: mixture
    sampling_rate: 40.0
  splits:
    train:
      include_mixtures: ["A", "B"]
    val:
      include_mixtures: ["C"]
    test:
      include_mixtures: ["D"]
  synthetic:
    enabled: true
    per_split:
      train: 2
      val: 1
      test: 1
    sensors: 7
    length: 220
    gases: [AMMONIA, PROPANE]

longterm:
  root: data/longterm
  files:
    pattern: "**/*.csv"
  mapping:
    dataset: LONG_TERM
    time: time
    sensor_cols: [L1, L2, L3, L4, L5, L6, L7, L8]
    gas: gas
    conc: concentration
    temp: temp
    humid: humid
    device_id: device
    session_id: session
    stage: stage
    batch_id: batch
    sampling_rate: 30.0
  splits:
    train:
      include_batches: [1, 2, 3]
    val:
      include_batches: [4]
    test:
      include_batches: [5]
  synthetic:
    enabled: true
    per_split:
      train: 2
      val: 1
      test: 1
    sensors: 8
    length: 260
    gases: [ETHANOL, TOLUENE]

pulses:
  root: data/pulses
  files:
    pattern: "**/*.csv"
  mapping:
    dataset: PULSES
    time: time
    sensor_cols: [P1, P2, P3, P4, P5]
    gas: gas
    conc: concentration
    temp: temp
    humid: humid
    device_id: device
    session_id: pulse
    stage: stage
    batch_id: batch
    sampling_rate: 60.0
  splits:
    train:
      include_pulses: ["train"]
    val:
      include_pulses: ["val"]
    test:
      include_pulses: ["test"]
  synthetic:
    enabled: true
    per_split:
      train: 2
      val: 1
      test: 1
    sensors: 5
    length: 180
    gases: [ETHANOL, ACETONE]
