seed: 1337
data_config: configs/data.yaml
prior_path: data/priors/prior.json
model:
  encoder: cnn1d
  hidden: 64
  prior_dim: 56
train:
  batch_size: 64
  max_epochs: 40
  lr: 3e-4
  weight_decay: 1e-4
loss:
  ce_weight: 1.0
  mse_weight: 0.3
  align_weight: 0.1
device: cuda
